name: Docker Image CI

on:
  push:
    branches: [ michael ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wrtc-xpra:$(date +%s)
